//Igor £onak
#include <iostream>

using namespace std;

int main()
{
   int x,i=0,k1,k2,k3,k4,k5,k6,k7,k8;
   char y1,y2;
   float a=0,b=0,c=0,d=0,e=0;
   float aw=0,al=0,ad=0;
   float bw=0,bl=0,bd=0;
   float cw=0,cl=0,cd=0;
   float dw=0,dl=0,dd=0;
   float ew=0,el=0,ed=0;
   int suma1=0,suma2=0;
   int w1=0,w2=0,d1=0,d2=0,l1=0,l2=0;
   cin>>x;

   while(i<x)
   {
       cin>>y1>>k1>>k2>>k3>>k4>>y2>>k5>>k6>>k7>>k8;
       suma1=k1+k2+k3+k4;
       suma2=k5+k6+k7+k8;
           if(k1!=k2&&k1!=k3&&k1!=k4&&k2!=k3&&k2!=k4&&k3!=k4) //   a1234   b cokolwiek
            {
                if(k5!=k6&&k5!=k7&&k5!=k8&&k6!=k7&&k6!=k8&&k7!=k8)
                {d1++;
                d2++;}
                else
                {
                    if(k5==k6&&k6==k7&&k7==k8)
                    {

                    }
                    else
                    {
                        w1++;
                        l2++;
                    }
                }
            }
           if((k1==k2&&k2==k3&&k3!=k4)||(k2==k3&&k3==k4&&k1!=k2)||(k1==k3&&k3==k4&&k1!=k2)||(k1==k2&&k2==k4&&k1!=k3)
              ||(k1==k2&&k2!=k3&&k3!=k4&&k2!=k4)||(k1==k3&&k3!=k2&&k3!=k4&&k2!=k4)||(k1==k4&&k2!=k4&&k3!=k4&&k2!=k3)
              ||(k2==k3&&k3!=k1&&k3!=k4&&k1!=k4)||(k2==k4&&k1!=k3&&k4!=k1&&k4!=k3)||(k3==k4&&k1!=k2&&k4!=k1&&k4!=k2)
              ||(k1==k2&&k3==k4&&k1!=k3)||(k1==k3&&k2==k4&&k1!=k2)||(k1==k4&&k2==k3&&k1!=k2))                                    //  a dwojka albo trojka  b 1234
            {if(k5!=k6&&k5!=k7&&k5!=k8&&k6!=k7&&k6!=k8&&k7!=k8)
           {
               l1++;
               w2++;
           }}

           if(k1==k2&&k2==k3&&k3==k4)           // dwie czworki
           {
                if(k5==k6&&k6==k7&&k7==k8)
               {if(suma1>suma2)
               {
                   w1++;
                   l2++;
               }
               if(suma1==suma2)
               {
                   d1++;
                   d2++;
               }
               if(suma1<suma2) {w2++;l1++;}}
               else{w1++;
               l2++;}
           }
           else{
           if(k5==k6&&k6==k7&&k7==k8)        // b czworka a cokolwiek
           {

               if(k1==k2&&k2==k3&&k3==k4)
               {if(suma1>suma2)
               {
                   w1++;
                   l2++;
               }
               if(suma1==suma2)
               {
                   d1++;
                   d2++;
               }
               if(suma1<suma2){w2++;l1++;}
           }
           else{w2++;l1++;}}}
           if((k1==k2&&k2==k3&&k3!=k4)||(k2==k3&&k3==k4&&k1!=k2)||(k1==k3&&k3==k4&&k1!=k2)||(k1==k2&&k2==k4&&k1!=k3)
                  ||(k1==k2&&k2!=k3&&k3!=k4&&k2!=k4)||(k1==k3&&k3!=k2&&k3!=k4&&k2!=k4)||(k1==k4&&k2!=k4&&k3!=k4&&k2!=k3)                        // a trojka albo para b dwie pary
              ||(k2==k3&&k3!=k1&&k3!=k4&&k1!=k4)||(k2==k4&&k1!=k3&&k4!=k1&&k4!=k3)||(k3==k4&&k1!=k2&&k4!=k1&&k4!=k2))
              {
                 if((k5==k6&&k7==k8&&k5!=k7)||(k5==k7&&k6==k8&&k5!=k6)||(k5==k8&&k6==k7&&k5!=k6))
                 {
                     w2++;
                     l1++;
                 }
              }
           if((k1==k2&&k3==k4&&k1!=k3)||(k1==k3&&k2==k4&&k1!=k2)||(k1==k4&&k2==k3&&k1!=k2))
           {
               if((k5==k6&&k6==k7&&k7!=k8)||(k6==k7&&k7==k8&&k5!=k6)||(k5==k7&&k7==k8&&k5!=k6)||(k5==k6&&k6==k8&&k5!=k7)
                  ||(k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)||(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)||(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)                        // a dwie pary b trojka albo para
              ||(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)||(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)||(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6))
              {
                  w1++;
                  l2++;
              }
              if((k5==k6&&k7==k8&&k6!=k7)||(k5==k7&&k6==k8&&k5!=k6)||(k5==k8&&k6==k7&&k5!=k6))     // a dwie pary b dwie pary
              {
                  if(suma1>suma2)
                  {
                      w1++;
                      l2++;
                  }
                  if(suma1==suma2)
                  {
                      if((k1==1||k2==1||k3==1||k4==1)&&(k1==4||k2==4||k3==4||k4==4))
                        {if((k5==1||k6==1||k7==1||k8==1)&&(k5==4||k6==4||k7==4||k8==4))
                      {
                          d1++;
                          d2++;
                      }
                      else{w1++;l2++;}}
                      else{d1++;d2++;}
                  }
                  if(suma1<suma2){l1++;w2++;}
              }

           }
           if((k1==k2&&k2!=k3&&k3!=k4&&k2!=k4)||(k1==k3&&k3!=k2&&k3!=k4&&k2!=k4)||(k1==k4&&k2!=k4&&k3!=k4&&k2!=k3)                        // a para b trojka
              ||(k2==k3&&k3!=k1&&k3!=k4&&k1!=k4)||(k2==k4&&k1!=k3&&k4!=k1&&k4!=k3)||(k3==k4&&k1!=k2&&k4!=k1&&k4!=k2))
              {if((k5==k6&&k6==k7&&k7!=k8)||(k6==k7&&k7==k8&&k5!=k6)||(k5==k7&&k7==k8&&k5!=k6)||(k5==k6&&k6==k8&&k5!=k7))
              {
                  w2++;
                  l1++;
              }}
           if((k1==k2&&k2==k3&&k3!=k4)||(k2==k3&&k3==k4&&k1!=k2)||(k1==k3&&k3==k4&&k1!=k2)||(k1==k2&&k2==k4&&k1!=k3))
           {
               if((k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)||(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)||(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)              // a trojka b para
              ||(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)||(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)||(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6))
              {
                  w1++;
                  l2++;

              }
              if((k5==k6&&k6==k7&&k7!=k8)||(k6==k7&&k7==k8&&k5!=k6)||(k5==k7&&k7==k8&&k5!=k6)||(k5==k6&&k6==k8&&k5!=k7))            // a trojka b trojka
              {
                  if(suma1>suma2)
                  {
                      w1++;
                      l2++;

                  }
                  if(suma1<suma2)
                  {
                      l1++;
                      w2++;
                  }
                  if(suma1==suma2)
                  {
                      if(suma1==7)
                        {if((k1==4||k2==4||k3==4||k4==4)&&(k1==1||k2==1||k3==1||k4==1))
                      {
                          if((k5==4||k6==4||k7==4||k8==4)&&(k5==1||k6==1||k7==1||k8==1))
                          {
                              d1++;
                              d2++;
                          }
                          else
                            {l1++;
                          w2++;}
                      }

                      else{d1++;d2++;}

                  }
                      if(suma1==10)
                      {
                         if((k1==4||k2==4||k3==4||k4==4)&&(k1==2||k2==2||k3==2||k4==2))
                            {
                                if((k5==4||k6==4||k7==4||k8==4)&&(k5==2||k6==2||k7==2||k8==2))
                        {d1++;
                        d2++;}
                        else
                          {l1++;
                          w2++;
                          }
                      }
                      else{d1++;d2++;}
                      }
                      if(suma1==13)
                         {
                         if((k1==4||k2==4||k3==4||k4==4)&&(k1==3||k2==3||k3==3||k4==3))
                            {if((k5==4||k6==4||k7==4||k8==4)&&(k5==3||k6==3||k7==3||k8==3))
                          {d1++;
                          d2++;}
                          else{l1++;w2++;}
                      }
                      else{d1++;d2++;}

                      }
                      if(suma1!=7&&suma1!=10&&suma1!=13){d1++; d2++;}

                  }
              }
           }

    if(k1==k2&&k2!=k3&&k3!=k4&&k2!=k4)                                                // a para b para
           {
               if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k1<k5){w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                     if(suma1<suma2){l1++;w2++;}
                  }
                 if(k1<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k1>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k7)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k7){w2++;l1++;}
              }
           }
    if(k1==k3&&k3!=k2&&k3!=k4&&k2!=k4)
        {
            if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k1<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                 {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k1>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k7)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k1<k7){w2++;l1++;}
              }
        }
    if(k1==k4&&k2!=k4&&k3!=k4&&k2!=k3)
        {
            if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k1>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k5){w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k1>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k6)
                 {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                     if(suma1<suma2){l1++;w2++;}
                  }
                 if(k1<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k1>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k1==k7)
                {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k1<k7){w2++;l1++;}
              }
        }
    if(k2==k3&&k3!=k1&&k3!=k4&&k1!=k4)
        {
            if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                     if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k5) {w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k5){w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k2>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k6)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k2>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k6)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k2>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k7)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k2<k7){w2++;l1++;}
              }
        }
    if(k2==k4&&k1!=k3&&k4!=k1&&k4!=k3)
        {
            if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k2<k5){w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k2>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k5){w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k2>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k6)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k2>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k6)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                     if(suma1<suma2){l1++;w2++;}
                  }
                  if(k2<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k2>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k2==k7)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k2<k7){w2++;l1++;}
              }
        }
        if(k3==k4&&k1!=k2&&k4!=k1&&k4!=k2)
        {
            if  (k5==k6&&k6!=k7&&k7!=k8&&k6!=k8)

              {
                  if(k3>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k5)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                 if(k3<k5){w2++;l1++;}
              }
              if(k5==k7&&k7!=k6&&k7!=k8&&k6!=k8)
              {
                   if(k3>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k5)
                 {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k3<k5){w2++;l1++;}
              }
              if(k5==k8&&k6!=k8&&k7!=k8&&k6!=k7)
              {
                  if(k3>k5)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k5)
                   {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k3<k5) {w2++;l1++;}
              }
              if(k6==k7&&k7!=k5&&k7!=k8&&k5!=k8)
              {
                  if(k3>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k6)
                 {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k3<k6){w2++;l1++;}
              }
              if(k6==k8&&k5!=k7&&k8!=k5&&k8!=k7)
              {
                  if(k3>k6)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k6)
                 {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                      if(suma1<suma2){l1++;w2++;}
                  }
                  if(k3<k6){w2++;l1++;}
              }
              if(k7==k8&&k5!=k6&&k8!=k5&&k8!=k6)
              {
                  if(k3>k7)
                  {
                      w1++;
                      l2++;
                  }
                  if(k3==k7)
                  {
                      if(suma1>suma2)
                      {
                          w1++;
                          l2++;
                      }
                      if(suma1==suma2)
                      {
                        d1++;
                        d2++;
                        }
                     if(suma1<suma2){l1++;w2++;}
                  }
                  if(k3<k7){w2++;l1++;}
              }
        }
       if(y1=='a')
        {
        a++;
        aw+=w1;
        ad+=d1;
        al+=l1;
        }
        if(y2=='a')
        {
        a++;
        aw+=w2;
        ad+=d2;
        al+=l2;
        }
        if(y1=='b')
        {
            b++;
            bw+=w1;
            bd+=d1;
            bl+=l1;
        }
        if(y2=='b')
        {
            b++;
            bw+=w2;
            bd+=d2;
            bl+=l2;
        }
        if(y1=='c')
        {
            c++;
            cw+=w1;
            cd+=d1;
            cl+=l1;
        }
        if(y2=='c')
        {
            c++;
            cw+=w2;
            cd+=d2;
            cl+=l2;
        }
        if(y1=='d')
        {
            d++;
            dw+=w1;
            dd+=d1;
            dl+=l1;
        }
        if(y2=='d')
        {
            d++;
            dw+=w2;
            dd+=d2;
            dl+=l2;
        }
        if(y1=='e')
        {
            e++;
            ew+=w1;
            ed+=d1;
            el+=l1;
        }
          if(y2=='e')
        {
            e++;
            ew+=w2;
            ed+=d2;
            el+=l2;
        }
        w1=0;w2=0;d1=0;d2=0;l1=0;l2=0;

   i++;
   }

   if(a>0){
    cout<<"gracz a"<<endl;
    if (aw>0)
    {cout<<"    "<<"wygrane: "<<(aw/a)*100<<"%"<<endl;}
    if(ad>0){cout<<"    "<<"remisy: "<<(ad/a)*100<<"%"<<endl;}
    if(al>0){cout<<"    "<<"przegrane: "<<(al/a)*100<<"%"<<endl;}
    cout<<endl;
   }
    if(b>0){
    cout<<"gracz b"<<endl;
    if (bw>0)
    {cout<<"    "<<"wygrane: "<<(bw/b)*100<<"%"<<endl;}
    if(bd>0){cout<<"    "<<"remisy: "<<(bd/b)*100<<"%"<<endl;}
    if(bl>0){cout<<"    "<<"przegrane: "<<(bl/b)*100<<"%"<<endl;}
    cout<<endl;
   }
    if(c>0){
    cout<<"gracz c"<<endl;
    if (cw>0)
    {cout<<"    "<<"wygrane: "<<(cw/c)*100<<"%"<<endl;}
    if(cd>0){cout<<"    "<<"remisy: "<<(cd/c)*100<<"%"<<endl;}
    if(cl>0){cout<<"    "<<"przegrane: "<<(cl/c)*100<<"%"<<endl;}
    cout<<endl;
   }
    if(d>0){
    cout<<"gracz d"<<endl;
    if (dw>0)
    {cout<<"    "<<"wygrane: "<<(dw/d)*100<<"%"<<endl;}
    if(dd>0){cout<<"    "<<"remisy: "<<(dd/d)*100<<"%"<<endl;}
    if(dl>0){cout<<"    "<<"przegrane: "<<(dl/d)*100<<"%"<<endl;}
    cout<<endl;
   }
    if(e>0){
    cout<<"gracz e"<<endl;
    if (ew>0)
    {cout<<"    "<<"wygrane: "<<(ew/e)*100<<"%"<<endl;}
    if(ed>0){cout<<"    "<<"remisy: "<<(ed/e)*100<<"%"<<endl;}
    if(el>0){cout<<"    "<<"przegrane: "<<(el/e)*100<<"%"<<endl;}
    cout<<endl;
   }

    return 0;
}
